### ISSUE TITLE
Can not compile on Ubuntu or Windows Visual Studio 2022 environment

### ISSUE THREAD

**Issue by Balkoth** [pok3r-custom/pok3rtool#18]
Don't even know what to report, because there is no information on what version is supported.

**Comment by usrlocalben** [comment]
I tried various configs of vs2019/vs2022/msys2/mingw/etc and the failures are so noisy that I'm not motivated to dig in.

However, it appears to build w/o issue using gcc-8.3.0, e.g. in docker w/ `debian:buster`

It needs `libusb-devel` in addition to gcc/g++/cmake/etc

I moved the exe to a fedora39 system and it seems to work fine. I needed `libusb-compat-0.1` to satisfy the old libusb so reqs. I can't fully verify it because it turns out the po3kr I have is some kind of oddball composition -- claims to be RGB but it is not RGB hw.

**Comment by Balkoth** [comment]
Ok, there seems to be no interest, closing!
